# Hello Viji here 

This has Viji's contributions in building API wrapper using openai and 
LinkedIn job scraping.

## 01-Intro

All chapter sections start with a second-level (`##`) or higher heading followed by your section title, like the sections above and below here. You can have as many as you want within a chapter.

### An unnumbered section {-}

Chapters and sections are numbered by default. To un-number a heading, add a `{.unnumbered}` or the shorter `{-}` at the end of the heading, like in this section.

## 02 - Parts

|Date | Module | Activity | Outcome/Achievements| Additional info|
|:---:| :------|:--------| :------|:------|
|13-Jan-2023|NA|Initiation|Research on API and brainstorm with team||
|14,15-Jan-2023|NA|Initiation|Research on API and brainstorm with team||
|16-Jan-2023|NA|Initiation|Group discussion on next steps||
|16-Jan-2023|NA|Initiation|Contribution log creation and logging||
|17-Jan-2023|NA|Initiation|Researched different APIs available||
|17-Jan-2023|NA|Initiation|Confirmation on using openAI||
|18-Jan-2023|NA|Proposal|Created draft proposal||
|20-Jan-2023|NA|Proposal|Finished discussions and review on proposal. We considered using RapidAPI|
||||but dropped as we are not sure of the permissions and terms that come with it|
|21-Jan-2023||Design|Looking at next steps for designing the wrapper||
|26-Jan-2023||Coding|Verified scraping from different sites||
|26-Jan-2023||Coding|Not able to scrape from indeed due to security||
|26-Jan-2023||Coding|Able to scrape from LinkedIn only when logged in||
|27-Jan-2023||Coding|Created first scrape from LinkedIn to share for downstream||
|27-Jan-2023||Coding|Created code of conduct and sent for review to team||
|31-Jan-2023||Coding|Worked on fine tuning scraping and created full output today||
|01-Feb-2023||Coding|Worked on fine tuning scraping and error functions||
|02-Feb-2023||Unit test and CICD|Worked on unit test and CICD ||
|03-Feb-2023||Presentation|Draft presentation and project review with team||
|04-Feb-2023||Presentation|Adding more inputs||
|06-Feb-2023||Documentation|Finalize presentation||
|07-Feb-2023||Documentation|Review with team and submit presentations on Canvas||
|08-Feb-2023||Presentation|Prepare for final presentation||
|09-Feb-2023||Presentation|final presentation||
|09-Feb-2023||Documentation|Readme.md updates for project||
|09-Feb-2023||Final|Project final review with team and submission on Canvas!!!||
||||||
||Decisions|NA|Not to use RapidAPI as the sources are not known for righteous use||
||Decisions|NA|Other job sites do not provide job description so going with LinkedIn||
||Decisions|NA|Final plots and output to user - reviewed and decided as a team||

## 03-references
Add all outside references and biliography links

|Date | Link | Comments|
|:---:| :--------| :------|
|abc|||

## 04-dependencies, open questions and comments

Anything to communicate with other project members or consider for future.

|Date | Module | Description| Comments|
|:---:| :------|:------|:------|
||Job scraping|Linked in Easy apply||
||Job scraping|Indeed||
||Job output|Salary inputs and recommendations||
